"""Task texts for the mt50 split's image prompts: descriptions and short procedures per task.

As prompts.py, but objects are named by kind and shape only, never by color, since looks.py
recolors them. Training draws one description per row and adds one procedure half the time.
The procedures follow each expert's phases and gripper use (metaworld.policies), without
numbers. The split: TRAIN (38 tasks), and two held-out sets never trained on: T_COMP, a seen
scene with a motion seen only in other scenes, and T_OBJ, scenes never seen. T-vis is TRAIN
under looks.py's "test" looks. pick-out-of-hole and peg-unplug-side are left out: their
experts' soft labels do not solve them (tasks.py replay).
"""
import numpy as np

TRAIN = ("reach-v3", "reach-wall-v3", "push-v3", "push-wall-v3", "push-back-v3", "pick-place-v3", "pick-place-wall-v3",
         "bin-picking-v3", "basketball-v3", "soccer-v3", "sweep-v3", "sweep-into-v3", "shelf-place-v3", "hammer-v3",
         "assembly-v3", "disassemble-v3", "box-close-v3", "peg-insert-side-v3", "hand-insert-v3", "button-press-v3",
         "button-press-topdown-v3", "button-press-wall-v3", "button-press-topdown-wall-v3", "door-open-v3", "door-lock-v3",
         "door-unlock-v3", "drawer-open-v3", "window-open-v3", "window-close-v3", "handle-press-v3", "handle-press-side-v3",
         "handle-pull-v3", "plate-slide-v3", "plate-slide-back-v3", "plate-slide-side-v3", "lever-pull-v3", "dial-turn-v3",
         "stick-push-v3")
T_COMP = ("drawer-close-v3", "door-close-v3", "handle-pull-side-v3", "plate-slide-back-side-v3")
T_OBJ = ("faucet-open-v3", "faucet-close-v3", "coffee-button-v3", "coffee-push-v3", "coffee-pull-v3", "stick-pull-v3")

DESCRIPTIONS = {
    # ---------------- train
    "reach-v3": [
        "Move the gripper to the goal, the small sphere; it may be in the air.",
        "Bring the fingertips to the small ball floating above the table.",
        "Reach for the small sphere. The cylinder on the table is not the target.",
        "Go to the goal marker; nothing needs to be picked up.",
        "Touch the small sphere with the gripper.",
        "Put the gripper at the goal sphere and stay there.",
        "Move the tip of the gripper onto the small ball in the air.",
        "Reach the small floating sphere with the gripper.",
        "Bring the gripper to the goal point marked by a small sphere.",
        "Move the gripper to the marker and hold it there.",
    ],
    "reach-wall-v3": [
        "Reach the small sphere behind the wall with the gripper.",
        "Move the gripper to the goal on the far side of the low wall.",
        "Get the fingertips to the small ball beyond the wall, going over the wall.",
        "The goal sphere is behind a wall. Reach it without hitting the wall.",
        "Bring the gripper over the wall to the small sphere.",
        "Touch the goal marker on the other side of the wall.",
        "Reach over the wall to the small ball.",
        "Move the gripper past the wall to the goal point.",
        "Go around the top of the wall and reach the sphere.",
        "Put the gripper at the small sphere that sits behind the wall.",
    ],
    "push-v3": [
        "Push the puck across the table to the goal, the small sphere.",
        "Slide the puck along the table until it reaches the goal marker.",
        "Move the cylinder on the table over to the small sphere by pushing it.",
        "The goal is the small sphere. Push the puck there without lifting it.",
        "Get the puck to the goal by sliding it along the tabletop.",
        "Shove the puck across the table so that it ends up at the goal marker.",
        "Bring the cylinder to the small sphere, keeping it on the table the whole way.",
        "Push the puck across the table to the goal.",
        "Slide the puck along the tabletop until it sits at the goal.",
        "Move the short cylinder to the small sphere by pushing it on the table.",
    ],
    "push-wall-v3": [
        "Push the puck around the wall to the goal.",
        "Slide the puck along the table past the wall to the small sphere.",
        "There is a wall between the puck and the goal. Push the puck around it.",
        "Get the cylinder to the goal marker, going around the wall.",
        "Move the puck on the table to the goal without hitting the wall.",
        "Push the puck to the goal sphere behind the wall.",
        "Slide the cylinder around the side of the wall to the goal.",
        "Bring the puck past the wall to the small sphere.",
        "Push the puck along the table, around the wall, to the marker.",
        "Steer the puck around the wall to the goal.",
    ],
    "push-back-v3": [
        "Push the puck back toward the robot to the goal.",
        "Slide the puck along the table toward the robot until it reaches the goal marker.",
        "Bring the cylinder back to the small sphere near the robot.",
        "Move the puck toward the robot's side of the table, to the goal.",
        "Pull the puck along the table back to the goal.",
        "The goal is closer to the robot. Slide the puck there.",
        "Drag the puck across the table toward the robot, to the marker.",
        "Get the cylinder back to the goal sphere.",
        "Move the puck backward along the table to the goal.",
        "Slide the puck to the goal on the robot's side.",
    ],
    "pick-place-v3": [
        "Pick up the puck and place it at the goal, the small sphere; the goal may be in the air.",
        "Grab the puck and carry it to the goal marker.",
        "Lift the cylinder off the table and bring it to the small sphere.",
        "Take the puck from the table and hold it at the goal sphere.",
        "Grasp the cylinder and move it to where the small ball is.",
        "Carry the puck through the air to the goal.",
        "Pick the puck up and put it at the marker.",
        "Pick up the puck and place it at the goal point.",
        "Grasp the cylinder on the table and carry it to the small sphere.",
        "Lift the puck and bring it to the goal.",
    ],
    "pick-place-wall-v3": [
        "Pick up the puck, lift it over the wall and place it at the goal.",
        "Carry the puck over the wall to the small sphere.",
        "Grab the cylinder and bring it to the goal on the other side of the wall.",
        "Lift the puck high enough to clear the wall, then put it at the goal.",
        "Take the puck over the wall to the goal marker.",
        "Grasp the puck and move it past the wall to the goal.",
        "Pick up the cylinder and carry it over the wall to the small ball.",
        "The goal is behind a wall. Lift the puck over it and place it there.",
        "Pick up the puck and bring it over the wall to the goal point.",
        "Carry the puck through the air, over the wall, to the goal.",
    ],
    "bin-picking-v3": [
        "Move the cube from one bin to the other.",
        "Pick up the small cube in the bin and drop it into the other bin.",
        "Take the block out of its bin and put it in the empty bin.",
        "Transfer the cube between the two bins.",
        "Lift the cube from the first bin and place it in the second.",
        "Grab the small block and carry it over to the other bin.",
        "Put the cube into the other bin.",
        "Move the block across to the empty bin.",
        "Pick the cube out of the bin and drop it in the bin beside it.",
        "Carry the small cube to the other container.",
    ],
    "basketball-v3": [
        "Put the ball through the hoop.",
        "Pick up the basketball and dunk it into the hoop in front of the backboard.",
        "Grab the ball and drop it into the basket.",
        "Score: lift the ball and put it in the hoop.",
        "Take the ball from the table and place it through the basketball hoop.",
        "Carry the ball up to the hoop and drop it in.",
        "Lift the ball into the ring in front of the board.",
        "Pick up the ball and dunk it into the basket.",
        "Grab the ball and drop it in the hoop.",
        "Raise the ball to the hoop and put it through.",
    ],
    "soccer-v3": [
        "Kick the ball into the goal net.",
        "Push the soccer ball along the table into the net.",
        "Score: roll the ball into the goal.",
        "Drive the ball into the small goal on the table.",
        "Get the ball into the net by pushing it.",
        "Knock the ball into the goal.",
        "Push the ball across the table so it goes into the net.",
        "Move the ball into the soccer goal.",
        "Shoot the ball into the net.",
        "Roll the ball along the table into the goal frame.",
    ],
    "sweep-v3": [
        "Sweep the small cube off the side of the table.",
        "Move the cube to the edge of the table and drop it off.",
        "Get the small block off the table at its side.",
        "Carry the cube along the table and let it fall off the edge.",
        "Clear the cube off the table to the side.",
        "Push the little box over the edge of the table.",
        "Take the cube to the table's edge and let go of it there.",
        "Sweep the cube off the table.",
        "Move the small block to the edge and drop it off.",
        "Get the cube off the side of the table.",
    ],
    "sweep-into-v3": [
        "Sweep the small cube into the hole in the table.",
        "Move the cube into the hole marked on the tabletop.",
        "Get the small block into the hole in the table.",
        "Carry the cube along the table and drop it into the hole.",
        "Put the cube in the hole on the table.",
        "Slide the little box into the opening in the table.",
        "Bring the cube to the hole and let it fall in.",
        "Sweep the cube into the hole.",
        "Move the block over to the hole and drop it in.",
        "Get the cube into the opening on the tabletop.",
    ],
    "shelf-place-v3": [
        "Pick up the cube and put it on the shelf.",
        "Place the block on the shelf at the goal marker.",
        "Lift the cube off the table and set it on the shelf.",
        "Put the small block onto the shelf.",
        "Carry the cube up to the shelf and leave it there.",
        "Grab the block and place it on the wooden shelf.",
        "Move the cube from the table onto the shelf.",
        "Put the cube on the shelf.",
        "Take the block and set it on the shelf's level.",
        "Place the cube on the shelf at the small sphere.",
    ],
    "hammer-v3": [
        "Use the hammer to drive the nail into the box.",
        "Pick up the hammer and hit the nail in.",
        "Grab the hammer by its handle and hammer the nail.",
        "Hammer the nail into the wall of the box.",
        "Lift the hammer and knock the nail in.",
        "Take the hammer and drive in the nail sticking out of the box.",
        "Hit the nail with the hammer until it goes in.",
        "Hammer in the nail.",
        "Pick up the hammer and strike the nail.",
        "Use the hammer on the nail.",
    ],
    "assembly-v3": [
        "Put the ring onto the peg.",
        "Pick up the wrench and fit its ring over the peg.",
        "Place the ring handle on the peg.",
        "Lift the wrench and drop its ring onto the post.",
        "Assemble: put the ring of the wrench around the peg.",
        "Grab the wrench by its handle and slide the ring down the peg.",
        "Carry the ring over to the peg and lower it on.",
        "Put the wrench's ring on the post.",
        "Fit the ring over the peg.",
        "Move the ring onto the peg.",
    ],
    "disassemble-v3": [
        "Take the ring off the peg.",
        "Lift the wrench's ring up off the post.",
        "Pull the ring handle off the peg.",
        "Disassemble: remove the wrench from the peg.",
        "Grab the wrench and lift it off the peg.",
        "Pull the ring up and off the post.",
        "Remove the ring from the peg.",
        "Lift the wrench off the peg.",
        "Take the ring off the post.",
        "Get the wrench's ring off the peg.",
    ],
    "box-close-v3": [
        "Put the lid on the box.",
        "Pick up the lid by its handle and close the box with it.",
        "Close the box: place the lid on top.",
        "Lift the lid and set it onto the box.",
        "Cover the box with its lid.",
        "Grab the lid's handle and put the lid on the box.",
        "Carry the lid over to the box and put it on.",
        "Close the box with the lid.",
        "Place the lid on top of the box.",
        "Put the cover on the box.",
    ],
    "peg-insert-side-v3": [
        "Insert the peg into the hole in the side of the box.",
        "Pick up the peg and push it into the hole in the box's side.",
        "Grab the stick and slide it sideways into the hole of the box.",
        "Put the peg into the side hole of the box.",
        "Lift the peg and insert it into the opening on the side of the box.",
        "Take the peg from the table and fit it into the hole in the box.",
        "Grasp the rod and push it into the side of the box through its hole.",
        "Insert the peg into the box's side hole.",
        "Pick up the peg and slide it into the hole.",
        "Grab the peg and fit it into the opening in the box.",
    ],
    "hand-insert-v3": [
        "Put the object into the hole in the table.",
        "Pick up the object and drop it into the hole.",
        "Move the object on the table into the hole.",
        "Grab the object and insert it into the opening in the table.",
        "Carry the object to the hole and put it in.",
        "Place the object in the hole.",
        "Lift the object and lower it into the hole in the table.",
        "Insert the object into the hole.",
        "Take the object to the opening and put it in.",
        "Put the block into the hole in the tabletop.",
    ],
    "button-press-v3": [
        "Press the button on the front of the box.",
        "Push the button in, from the robot's side.",
        "Press the button that faces the robot.",
        "Push the button on the box's front face.",
        "Press in the button, moving away from the robot.",
        "The box has a button facing you. Press it.",
        "Push the button forward until it is pressed.",
        "Press the button.",
        "Push in the button on the box.",
        "Press the front button.",
    ],
    "button-press-topdown-v3": [
        "Press the button on top of the box.",
        "Push the button down from above.",
        "Press down on the button on the box.",
        "The box has a button on top. Push it down.",
        "Press the button on the box straight down.",
        "Push the knob on the box down until it clicks.",
        "Press the button from above with the gripper.",
        "Press the top button.",
        "Push the button down.",
        "Press down on the button until it is pushed in.",
    ],
    "button-press-wall-v3": [
        "Press the button behind the wall.",
        "Reach over the wall and push the button on the box.",
        "Go over the wall and press the front button.",
        "The button is behind a wall. Press it.",
        "Get past the wall and push the button in.",
        "Press the box's button, going around the wall.",
        "Push the button that sits behind the wall.",
        "Clear the wall and press the button.",
        "Press the button beyond the wall.",
        "Reach the button behind the wall and push it in.",
    ],
    "button-press-topdown-wall-v3": [
        "Press the button on top of the box behind the wall.",
        "Push the top button down; there is a wall in front of it.",
        "Reach over the wall and press the button down from above.",
        "Press down on the button behind the wall.",
        "The box behind the wall has a button on top. Push it down.",
        "Press the top button, past the wall.",
        "Go above the button behind the wall and press it down.",
        "Push down the button beyond the wall.",
        "Press the button on the box from above.",
        "Push the top button in, clearing the wall.",
    ],
    "door-open-v3": [
        "Open the cabinet door by pulling its handle.",
        "Swing the cabinet door open.",
        "Pull the handle of the cabinet so that the door opens.",
        "The cabinet has a closed door. Open it.",
        "Open the safe's door by dragging its handle sideways.",
        "Pull the door open until it reaches the goal marker.",
        "Get the door of the cabinet to swing open.",
        "Open the door with its handle.",
        "Swing the door open using its handle.",
        "Pull the door of the cabinet open.",
    ],
    "door-lock-v3": [
        "Lock the door by turning the lock knob.",
        "Turn the lock on the cabinet door to lock it.",
        "Push the lock knob on the door down to lock it.",
        "Lock the cabinet door.",
        "Turn the knob on the door to the locked position.",
        "Rotate the door's lock so the door is locked.",
        "Press the lock lever on the door down.",
        "Lock the door using its knob.",
        "Turn the lock knob to lock the door.",
        "Set the door's lock.",
    ],
    "door-unlock-v3": [
        "Unlock the door by turning the lock knob.",
        "Turn the lock on the cabinet door to unlock it.",
        "Push the lock knob on the door sideways to unlock it.",
        "Unlock the cabinet door.",
        "Turn the knob on the door to the unlocked position.",
        "Rotate the door's lock so the door is unlocked.",
        "Release the lock on the door.",
        "Unlock the door using its knob.",
        "Turn the lock knob to unlock the door.",
        "Open the door's lock.",
    ],
    "drawer-open-v3": [
        "Open the drawer by pulling its handle toward the robot.",
        "Pull the drawer out of the cabinet.",
        "Slide the drawer open with its handle.",
        "The drawer is closed. Pull it open.",
        "Pull the handle so the drawer comes out toward the robot.",
        "Open the box's drawer.",
        "Draw the drawer out by its handle.",
        "Open the drawer.",
        "Pull the drawer open.",
        "Pull the handle to open the drawer.",
    ],
    "window-open-v3": [
        "Open the window: slide the pane sideways.",
        "Slide the window open by its handle.",
        "Push the window's handle sideways so that the window opens.",
        "The window is closed. Slide it open.",
        "Open the sliding window by moving its handle along the frame.",
        "Slide the pane of the window aside to open it.",
        "Move the window handle sideways until the window is open.",
        "Slide the window open.",
        "Open the window by sliding its handle.",
        "Push the sliding window open along its frame.",
    ],
    "window-close-v3": [
        "Close the window: slide the pane back.",
        "Slide the window shut by its handle.",
        "Push the window's handle sideways so that the window closes.",
        "The window is open. Slide it closed.",
        "Close the sliding window by moving its handle along the frame.",
        "Slide the pane of the window back to close it.",
        "Move the window handle sideways until the window is shut.",
        "Slide the window closed.",
        "Close the window by sliding its handle.",
        "Push the sliding window shut along its frame.",
    ],
    "handle-press-v3": [
        "Press the handle down.",
        "Push the handle on the box all the way down.",
        "Press down on the lever handle.",
        "The handle sticks up. Push it down.",
        "Press the handle of the box downward.",
        "Push down on the handle until it stops.",
        "Lower the handle by pressing on it.",
        "Press the handle down from above.",
        "Push the handle down.",
        "Press down the handle.",
    ],
    "handle-press-side-v3": [
        "Press down the handle on the side of the box.",
        "Push the side handle of the box down.",
        "Press down on the handle sticking out of the box's side.",
        "The box has a handle on its side. Push it down.",
        "Lower the side handle by pressing on it.",
        "Press the side handle all the way down.",
        "Push down on the handle at the side of the box.",
        "Press the side handle down.",
        "Push the handle on the side down.",
        "Press down the box's side handle.",
    ],
    "handle-pull-v3": [
        "Pull the handle up.",
        "Lift the handle on the box all the way up.",
        "Pull up on the lever handle.",
        "The handle is down. Pull it up.",
        "Raise the handle of the box.",
        "Pull the handle upward until it stops.",
        "Lift the handle by pulling it up.",
        "Pull up the handle.",
        "Raise the handle.",
        "Lift the handle up.",
    ],
    "plate-slide-v3": [
        "Slide the plate into the goal cage.",
        "Push the plate across the table into the net.",
        "Slide the flat plate away from the robot into the goal.",
        "Get the plate into the cage by sliding it.",
        "Push the plate along the table into the goal frame.",
        "Move the plate into the net, sliding it on the table.",
        "Shove the plate into the cage.",
        "Slide the plate into the goal.",
        "Push the plate into the net.",
        "Slide the disk across the table into the cage.",
    ],
    "plate-slide-back-v3": [
        "Slide the plate out of the cage back toward the robot.",
        "Pull the plate out of the net to the goal.",
        "Drag the plate back out of the goal cage.",
        "Get the plate out of the cage by sliding it back.",
        "Pull the plate along the table away from the net.",
        "Move the plate out of the cage toward the robot.",
        "Slide the plate back out of the goal frame.",
        "Pull the plate out of the cage.",
        "Slide the plate back to the goal.",
        "Drag the disk out of the net.",
    ],
    "plate-slide-side-v3": [
        "Slide the plate sideways into the goal cage.",
        "Push the plate to the side into the net.",
        "Slide the flat plate sideways along the table into the goal.",
        "Get the plate into the cage at the side by sliding it.",
        "Push the plate sideways into the goal frame.",
        "Move the plate into the net on its side.",
        "Shove the plate sideways into the cage.",
        "Slide the plate into the goal at the side.",
        "Push the plate sideways into the net.",
        "Slide the disk sideways into the cage.",
    ],
    "lever-pull-v3": [
        "Pull the lever up: lift the lever arm on the stand so that it points upward.",
        "Raise the lever on the post until it swings up.",
        "The lever sticks out from the stand with a ball at its end. Rotate it upward.",
        "Lift the lever up.",
        "Swing the lever arm upward.",
        "Pull the lever on the stand up.",
        "Raise the lever until it points up.",
        "Pull the lever up.",
        "Lift the lever arm.",
        "Turn the lever upward.",
    ],
    "dial-turn-v3": [
        "Turn the dial.",
        "Rotate the knob on the table.",
        "Spin the dial around.",
        "Turn the round knob.",
        "Rotate the dial with the gripper.",
        "Twist the dial on the table.",
        "Turn the knob to a new position.",
        "Rotate the dial.",
        "Spin the knob.",
        "Turn the dial knob.",
    ],
    "stick-push-v3": [
        "Use the stick to push the container to the goal.",
        "Pick up the stick and push the thermos with it.",
        "Grab the stick and shove the container along the table.",
        "Push the container to the goal using the stick.",
        "Take the stick and use it to move the thermos away.",
        "With the stick, push the container forward.",
        "Pick up the stick and push the container to the marker.",
        "Push the thermos with the stick.",
        "Use the stick as a tool to push the container.",
        "Grab the stick and push the container with it.",
    ],
    # ---------------- test, T-comp
    "drawer-close-v3": [
        "Close the drawer: push the open drawer shut.",
        "Push the drawer back into the cabinet.",
        "Close the drawer.",
    ],
    "door-close-v3": [
        "Close the open door of the cabinet.",
        "Swing the cabinet's door shut.",
        "Close the cabinet door.",
    ],
    "handle-pull-side-v3": [
        "Pull up the handle on the side of the box.",
        "Lift the side handle of the box.",
        "Pull the side handle up.",
    ],
    "plate-slide-back-side-v3": [
        "Slide the plate sideways out of the goal cage.",
        "Pull the plate out of the net to the side.",
        "Slide the plate out of the cage sideways.",
    ],
    # ---------------- test, T-obj
    "faucet-open-v3": [
        "Open the faucet: turn its handle.",
        "Turn the tap handle to open the faucet.",
        "Open the faucet.",
    ],
    "faucet-close-v3": [
        "Close the faucet: turn its handle back.",
        "Turn the tap handle to close the faucet.",
        "Close the faucet.",
    ],
    "coffee-button-v3": [
        "Press the button on the coffee machine.",
        "Push the coffee machine's button.",
        "Press the coffee button.",
    ],
    "coffee-push-v3": [
        "Push the mug under the coffee machine.",
        "Slide the cup to the coffee machine's spout.",
        "Move the mug to the coffee machine.",
    ],
    "coffee-pull-v3": [
        "Pull the mug out from the coffee machine.",
        "Slide the cup away from the coffee machine toward the robot.",
        "Move the mug away from the coffee machine.",
    ],
    "stick-pull-v3": [
        "Use the stick to pull the container toward the goal.",
        "Pick up the stick, hook the thermos and drag it.",
        "Pull the container with the stick.",
    ],
}

PROCEDURES = {
    # ---------------- train
    "reach-v3": [
        "Move straight to the goal with the gripper open.",
        "Keep the gripper open and go to the sphere.",
        "Head for the goal and stop there.",
        "Go directly to the target; do not close the gripper.",
        "Move to the goal and hold still.",
    ],
    "reach-wall-v3": [
        "Keep the gripper open, rise above the wall, then move to the goal.",
        "Go up over the wall and come down at the sphere.",
        "Move toward the goal, climbing over the wall on the way.",
        "Lift the gripper above the wall, pass it, then reach the goal.",
        "Head for the goal, going over the wall rather than into it.",
    ],
    "push-v3": [
        "Move above the puck, lower onto it and close the gripper, then push it along the table to the goal.",
        "Get over the puck, go down around it, grip it, and slide it to the goal while staying low.",
        "Line up above the puck, descend and grasp it, then drag it to the goal.",
        "Go over the puck, drop down, close the fingers, and move it to the goal on the table.",
        "Position above the puck, lower and close the gripper, then push to the goal.",
    ],
    "push-wall-v3": [
        "Move above the puck, lower and grip it, then push it around the side of the wall to the goal.",
        "Grasp the puck from above, steer it around the wall, then on to the goal.",
        "Get over the puck, go down and close the gripper, go around the wall, then to the goal.",
        "Grip the puck, move it sideways past the wall, then forward to the goal.",
        "Lower onto the puck and grasp it; push it around the wall and to the goal.",
    ],
    "push-back-v3": [
        "Move above the puck, lower and grip it, then move it back toward the robot to the goal.",
        "Grasp the puck from above and drag it toward the robot to the goal.",
        "Get over the puck, go down and close the gripper, then pull it to the goal.",
        "Grip the puck and slide it backward along the table to the goal.",
        "Lower onto the puck, grasp it, and bring it back to the goal.",
    ],
    "pick-place-v3": [
        "Move above the puck, lower and close the gripper, wait until it has closed, then carry it to the goal.",
        "Get over the puck, go down and grasp it, then lift it to the goal.",
        "Line up above the puck, descend and grip it, then move it to the goal.",
        "Go over the puck, drop down, close the fingers, and bring it to the goal.",
        "Position above the puck, lower and grasp it, then carry it to the goal.",
    ],
    "pick-place-wall-v3": [
        "Move above the puck, lower and grasp it, lift it straight up over the wall, then carry it to the goal.",
        "Grasp the puck from above, raise it above the wall, then bring it to the goal.",
        "Get over the puck, go down and grip it, go up high, move past the wall, then to the goal.",
        "Pick up the puck, lift it clear of the wall, then place it at the goal.",
        "Grip the puck, rise over the wall, and move to the goal.",
    ],
    "bin-picking-v3": [
        "Move above the cube, lower and grasp it, lift it, carry it over the other bin, then lower it in.",
        "Grasp the cube from above, raise it, move over the empty bin, and put it down there.",
        "Get over the cube, go down and grip it, rise, go to the other bin, and lower.",
        "Pick up the cube, bring it above the second bin, and lower it into the bin.",
        "Grip the cube, lift it out of its bin, and set it into the other bin.",
    ],
    "basketball-v3": [
        "Move above the ball, lower and grasp it, lift it to the hoop's height, then move it into the hoop.",
        "Get over the ball, go down and grip it, raise it, and bring it to the hoop.",
        "Grasp the ball from above, lift it up, and carry it into the hoop.",
        "Go over the ball, lower, close the fingers, rise, and move to the hoop.",
        "Pick up the ball, raise it to the hoop, and put it in.",
    ],
    "soccer-v3": [
        "Keep the gripper closed. Get behind the ball, staying low, then push the ball toward the goal.",
        "With the fingers closed, move to the side of the ball away from the goal and drive it into the net.",
        "Close the gripper, go behind the ball, and push it straight at the goal.",
        "Keep the gripper closed, line up behind the ball, then push it into the net.",
        "Get to the far side of the ball from the goal, then push through the ball toward the goal.",
    ],
    "sweep-v3": [
        "Move above the cube, lower and grasp it, carry it to the table's edge, then open the gripper.",
        "Get over the cube, go down and grip it, move it to the edge, and let it go.",
        "Grasp the cube from above, bring it to the side of the table, and release it.",
        "Go over the cube, lower, close the fingers, and take it off the edge.",
        "Pick up the cube, move it past the edge, and drop it.",
    ],
    "sweep-into-v3": [
        "Move above the cube, lower and grasp it, then carry it along the table to the hole.",
        "Grasp the cube from above and bring it to the hole.",
        "Get over the cube, go down and grip it, and move it over the hole.",
        "Go over the cube, lower, close the fingers, and take it to the hole.",
        "Pick up the cube and move it to the hole.",
    ],
    "shelf-place-v3": [
        "Move above the cube, lower and grasp it, lift it to the shelf's height, then move it onto the shelf.",
        "Grasp the cube from above, raise it, and carry it onto the shelf.",
        "Get over the cube, go down and grip it, rise to the shelf, and push it in.",
        "Pick up the cube, bring it in line with the shelf, lift it, and set it on the shelf.",
        "Grip the cube, lift it up to the shelf level, and move it forward onto the shelf.",
    ],
    "hammer-v3": [
        "Move above the hammer's handle, lower and grasp it, raise it to the nail's height, then swing it into the nail.",
        "Grasp the hammer from above, lift it, line it up with the nail, and drive it in.",
        "Get over the handle, go down and grip it, move to the nail, and hit it.",
        "Pick up the hammer, bring it level with the nail, then push into the nail.",
        "Grip the hammer's handle, raise it, and strike the nail.",
    ],
    "assembly-v3": [
        "Move above the wrench, lower and grasp it, lift it to the peg's height, move over the peg, then lower the ring onto it.",
        "Grasp the wrench from above, raise it, line the ring up above the peg, and lower it down.",
        "Get over the wrench, go down and grip it, carry it above the peg, and drop the ring on.",
        "Pick up the wrench, bring its ring over the peg, and lower it.",
        "Grip the wrench, lift it, go over the peg, and put the ring down around it.",
    ],
    "disassemble-v3": [
        "Move above the wrench, lower and grasp it, then lift it straight up off the peg.",
        "Grasp the wrench from above and pull it up off the peg.",
        "Get over the wrench, go down and grip it, and raise it.",
        "Go over the wrench, lower, close the fingers, and lift up.",
        "Grip the wrench and pull the ring straight up.",
    ],
    "box-close-v3": [
        "Move above the lid, lower and grip its handle, lift it, carry it over the box, then put it down.",
        "Grasp the lid's handle from above, raise it, and place it on the box.",
        "Get over the lid, go down and close the gripper on the handle, move above the box, and lower.",
        "Pick up the lid by its handle, bring it over the box, and set it on.",
        "Grip the lid, lift it, go to the box, and put the lid on top.",
    ],
    "peg-insert-side-v3": [
        "Move above the peg, lower and grasp it, then carry it level with the hole and push it in.",
        "Get over the peg, go down and grip it, then bring it to the hole and slide it in.",
        "Grasp the peg from above, move it in line with the hole, then insert it.",
        "Go over the peg, lower, close the fingers, and push the peg into the hole.",
        "Pick up the peg, align it with the hole, and slide it in.",
    ],
    "hand-insert-v3": [
        "Move above the object, lower and grasp it, carry it over the hole, then lower it in.",
        "Grasp the object from above, bring it above the hole, and put it down into it.",
        "Get over the object, go down and grip it, move over the hole, and lower.",
        "Pick up the object, carry it to the hole, and lower it in.",
        "Grip the object, move it above the hole, and drop it in.",
    ],
    "button-press-v3": [
        "Keep the gripper open, line up with the button, then push forward into it.",
        "Get in front of the button at its height, then move straight toward it.",
        "Align with the button from the robot's side, then press forward.",
        "Move to the button's height in front of it and push it in.",
        "Face the button, then push forward until it is pressed.",
    ],
    "button-press-topdown-v3": [
        "Move above the button, then push straight down.",
        "Go over the button and press down.",
        "Line up above the button and lower onto it.",
        "Get above the button and push down.",
        "Move over the button and press it down.",
    ],
    "button-press-wall-v3": [
        "Go up high, move over the wall, come down in front of the button, then push it with the gripper open.",
        "Line up with the button, rise over the wall, drop to the button's height, and press forward.",
        "Clear the wall from above, get in front of the button, and push it in.",
        "Move high over the wall to the button, lower, open the fingers, and press forward.",
        "Rise above the wall, move beyond it to the button, and push the button in.",
    ],
    "button-press-topdown-wall-v3": [
        "Keep the gripper open, move above the button past the wall, then push straight down.",
        "Go over the wall to above the button and press down.",
        "Line up above the button behind the wall and lower onto it.",
        "Get above the button, clearing the wall, and push down.",
        "Move over the button beyond the wall and press it down.",
    ],
    "door-open-v3": [
        "Keep the gripper closed. Move above and beside the handle, lower to it, then pull the door open.",
        "With the fingers closed, go to the handle from above, drop down to it, and drag it to open the door.",
        "Close the gripper, get next to the handle, lower to handle height, and pull the door open.",
        "Keep the gripper closed, reach the handle from above, then pull it sideways.",
        "Go above the handle with a closed gripper, come down to it, and pull the door open.",
    ],
    "door-lock-v3": [
        "Keep the gripper open, move above the lock knob, lower to it, then push it sideways and down.",
        "Go over the lock, drop to it, and press it down to the side.",
        "Get above the knob, lower onto it, and turn it by pushing sideways and down.",
        "Move to the lock from above and push it down sideways.",
        "Reach the knob from above, then press it down and aside.",
    ],
    "door-unlock-v3": [
        "Keep the gripper closed, go to the lock knob, then push it sideways.",
        "With the fingers closed, move to the knob and push it to the side.",
        "Close the gripper, reach the lock, and turn it by pushing sideways.",
        "Get to the knob with a closed gripper and push it aside.",
        "Keep the gripper closed, move onto the lock, and push it sideways.",
    ],
    "drawer-open-v3": [
        "Keep the gripper open, move high above the handle, lower to it, then pull toward the robot.",
        "Go above the handle with an open gripper, come down to it, and pull the drawer out.",
        "With the fingers open, get over the handle, drop down, and pull it toward the robot.",
        "Rise above the handle, lower onto it, and draw the drawer out.",
        "Keep the gripper open, go down to the handle from above, and pull back.",
    ],
    "window-open-v3": [
        "Keep the gripper closed, move above the handle, lower to it, then push it sideways.",
        "With the fingers closed, come down to the handle and slide it along the frame.",
        "Close the gripper, get to the handle from above, and push it to the side.",
        "Keep the gripper closed. Go over the handle, drop to it, and slide the window open.",
        "Close the gripper, lower onto the handle, and move it sideways.",
    ],
    "window-close-v3": [
        "Keep the gripper closed, move above the handle, lower to it, then push it back sideways.",
        "With the fingers closed, come down beside the handle and slide it the other way along the frame.",
        "Close the gripper, get to the handle from above, and push it back to close the window.",
        "Keep the gripper closed. Go over the handle, drop to it, and slide the window shut.",
        "Close the gripper, lower beside the handle, and push it sideways to close.",
    ],
    "handle-press-v3": [
        "Keep the gripper open, move above the handle, then push straight down.",
        "Go high over the handle and press it down.",
        "Line up above the handle and lower onto it until it is down.",
        "Get above the handle and push down.",
        "Move over the handle and press it all the way down.",
    ],
    "handle-press-side-v3": [
        "Keep the gripper closed, move high above the side handle, then push straight down.",
        "With the fingers closed, go over the side handle and press it down.",
        "Close the gripper, line up above the side handle, and lower onto it.",
        "Get above the side handle with a closed gripper and push down.",
        "Keep the gripper closed, move over the side handle, and press it down.",
    ],
    "handle-pull-v3": [
        "Keep the gripper closed, move under the handle's end, then pull straight up.",
        "With the fingers closed, get just below the handle and lift it up.",
        "Close the gripper, go to the handle at its height, and raise it.",
        "Get under the handle with a closed gripper and push up.",
        "Keep the gripper closed, reach below the handle, and lift.",
    ],
    "plate-slide-v3": [
        "Keep the gripper open, move behind the plate on the robot's side, lower, then push it forward into the cage.",
        "Get to the near side of the plate, drop down, and slide it away into the net.",
        "Go above the side of the plate nearest the robot, lower, and push it forward.",
        "Lower behind the plate and push it away from the robot into the goal.",
        "Get behind the plate, go down, and slide it forward into the cage.",
    ],
    "plate-slide-back-v3": [
        "Keep the gripper open, move to the robot's side of the plate, lower, then pull it back toward the robot.",
        "Get over the near side of the plate, drop down, and drag it back out of the cage.",
        "Go above the plate's near edge, lower, and pull it toward the robot, then to the goal.",
        "Lower at the near side of the plate and pull it back out of the net.",
        "Reach the plate's near edge from above and drag it back to the goal.",
    ],
    "plate-slide-side-v3": [
        "Keep the gripper closed, move beside the plate, lower, then push it sideways into the cage.",
        "With the fingers closed, get to the plate's side, drop down, and slide it into the net.",
        "Close the gripper, go above the far side of the plate, lower, and push it sideways.",
        "Lower beside the plate with a closed gripper and push it to the side into the goal.",
        "Keep the gripper closed, get next to the plate, go down, and slide it sideways.",
    ],
    "lever-pull-v3": [
        "Keep the gripper closed. Move to just below the lever's end, rise up to it, then push forward and up.",
        "With the fingers closed, go under the end of the lever and lift it.",
        "Close the gripper, get below the lever, come up to it, and push it upward.",
        "Keep the gripper closed, reach under the lever's end, and raise it.",
        "Go below the lever with a closed gripper and lift it up and away.",
    ],
    "dial-turn-v3": [
        "Keep the gripper closed, move above the edge of the dial, lower, then push sideways to turn it.",
        "With the fingers closed, go over the side of the knob, drop down, and sweep sideways.",
        "Close the gripper, get above the dial's edge, lower, and push across it.",
        "Keep the gripper closed, come down at the edge of the dial, and move sideways.",
        "Lower onto the dial's edge with a closed gripper and push it around.",
    ],
    "stick-push-v3": [
        "Move above the stick, lower and grasp it, bring it in line with the container, then push the container to the goal.",
        "Grasp the stick from above, line it up with the container, and push the container away.",
        "Get over the stick, go down and grip it, move to the container, and shove it to the goal.",
        "Pick up the stick, align it with the container, then drive the container forward.",
        "Grip the stick, bring it to the container, and push the container with it.",
    ],
    # ---------------- test, T-comp
    "drawer-close-v3": [
        "Keep the gripper closed, get in front of the handle, and push the drawer in.",
        "With the fingers closed, come to the handle from above and push the drawer shut.",
    ],
    "door-close-v3": [
        "Keep the gripper closed. Get beside the open door from above, lower to it, then push it shut.",
        "With the fingers closed, come down next to the door and push it closed.",
    ],
    "handle-pull-side-v3": [
        "Move above the side handle, lower and grasp it, then pull straight up.",
        "Grasp the side handle from above and lift it up.",
    ],
    "plate-slide-back-side-v3": [
        "Keep the gripper closed, move beside the plate, lower, then push it sideways out of the cage.",
        "With the fingers closed, get to the plate's side and slide it out of the net sideways.",
    ],
    # ---------------- test, T-obj
    "faucet-open-v3": [
        "Keep the gripper closed, move above one side of the handle, lower, then push it sideways to turn it.",
        "With the fingers closed, come down beside the faucet handle and push it around.",
    ],
    "faucet-close-v3": [
        "Keep the gripper closed, move above the other side of the handle, lower, then push it sideways to turn it back.",
        "With the fingers closed, come down beside the faucet handle and push it the other way.",
    ],
    "coffee-button-v3": [
        "Keep the gripper open, line up with the button on the machine, then push forward into it.",
        "Get in front of the machine's button at its height and press forward.",
    ],
    "coffee-push-v3": [
        "Move above the mug, lower and grasp it, then carry it low to the machine's spout.",
        "Grasp the mug from above and slide it under the machine.",
    ],
    "coffee-pull-v3": [
        "Move above the mug, lower and grasp it, then pull it away from the machine to the goal.",
        "Grasp the mug from above and bring it back toward the robot.",
    ],
    "stick-pull-v3": [
        "Move above the stick, lower and grasp it, hook it into the container's handle, then pull the container to the goal.",
        "Grasp the stick, bring it to the container, hook it, and drag the container.",
    ],
}


def text(task_name, rng, procedure):
    """A task text: a random description, with a random procedure when procedure is True."""
    lines = [f"Task: {rng.choice(DESCRIPTIONS[task_name])}"]
    if procedure:
        lines.append(f"Procedure: {rng.choice(PROCEDURES[task_name])}")
    return "\n".join(lines)
